;; key bindings
(global-set-key (kbd "C-x p") 'other-window-backward)
(global-set-key [f5] 'cbm-lisp-environment)
(global-set-key (kbd "C-c d") 'toggle-current-window-dedication)
(global-set-key [(control meta return)] 'toggle-fullscreen)
(global-set-key (kbd "C-w") 'backward-kill-word)
(global-set-key (kbd "C-x C-k") 'kill-region)
(global-set-key (kbd "C-q") 'scroll-lines-up)
(global-set-key (kbd "C-z") 'scroll-lines-down)
(global-set-key (kbd "C-x 3") 'split-window-horizontally-other)
(global-set-key (kbd "C-x 2") 'split-window-vertically-other)
